version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

# volumes:
#   volume1:
#     driver: local
# networks:
#   common:
#     driver: bridge
