version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: ./RABBIT/Dockerfile
    ports:
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
    env_file: .env

  mongo:
    image: mongo
    container_name: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./NODE/Dockerfile
    env_file: .env
    # links:
    #   - "mongo"
    #   - "rabbitmq"
    depends_on:
      - "mongo"
      - "rabbitmq"
    tty: true
    ports:
      - '4043:4043'
      - '8081:8081'
      - "3000:3000"
    command:  /app/wait-for-it/wait-for-it.sh rabbitmq:5672 --timeout=0 --strict -- make start-server 
    volumes: 
      - ./files:/var/files
      - ./newfiles:/var/newfiles

  users:
    container_name: users
    build:
      context: .
      dockerfile: ./NODE/Dockerfile
    env_file: .env
    # links:
    #   - "mongo"
    #   - "rabbitmq"
    depends_on:
      - "mongo"
      - "rabbitmq"
    tty: true
    # ports:
    #   - '4043:4043'
    command:  /app/wait-for-it/wait-for-it.sh rabbitmq:5672 --timeout=0 --strict -- make start-users 
    volumes: 
      - ./files:/var/files
      - ./newfiles:/var/newfiles

  filechanger:
    container_name: filechanger
    build:
      context: .
      dockerfile: ./NODE/Dockerfile
    env_file: .env
    # links:
    #   - "mongo"
    #   - "rabbitmq"
    depends_on:
      - "mongo"
      - "rabbitmq"
    tty: true
    # ports:
    #   - '4043:4043'
    command:  /app/wait-for-it/wait-for-it.sh rabbitmq:5672 --timeout=0 --strict -- make start-filechanger 
    volumes: 
      - ./files:/var/files
      - ./newfiles:/var/newfiles

  filewatcher:
    container_name: filewatcher
    build:
      context: .
      dockerfile: ./NODE/Dockerfile
    env_file: .env
    # links:
    #   - "mongo"
    #   - "rabbitmq"
    depends_on:
      - "mongo"
      - "rabbitmq"
    tty: true
    # ports:
    #   - '4043:4043'
    command:  /app/wait-for-it/wait-for-it.sh rabbitmq:5672 --timeout=0 --strict -- make start-filewatcher 
    volumes: 
      - ./files:/var/files
      - ./newfiles:/var/newfiles


# volumes:
#   volume1:
#     driver: local
# networks:
#   common:
#     driver: bridge
