version: '3'

services:
  rabbit:
    build:
      context: .
      dockerfile: ./RABBIT/Dockerfile
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file: .env

  node:
    container_name: node
    build:
      context: .
      dockerfile: ./NODE/Dockerfile
    env_file: .env
    depends_on:
      - rabbit
    tty: true
    ports:
      - '4043:4043'
    command:  /app/wait-for-it/wait-for-it.sh rabbit:5672 --timeout=0 --strict -- make start 
    volumes: 
      - ./files:/var/files
      - ./newfiles:/var/newfiles

# volumes:
#   volume1:
#     driver: local
# networks:
#   common:
#     driver: bridge
